# quin sheets llegir
sources_sheet:
  spreadsheet_title: "faqs-sources"
  worksheet_name: "sources"

# quin sheets escriure
google_sheets:
  spreadsheet_title: "Proves-faqs-mentors"
  worksheet_name: "FAQs"

# quines credencials usar
credentials_file: "Credentials.json"