TOPICS_UI = ["Graus", "Masters", "TFE", "Mobilitat", "Empresa", "Acte de graduaci\u00f3"]

OAUTH_HELP_TEXT = (
    "Com aconseguir oauth_client.json (Google OAuth):\n\n"
    "1) Ves a Google Cloud Console.\n"
    "2) Crea un projecte (o usa'n un existent).\n"
    "3) APIs & Services -> Library:\n"
    "   - Habilita Google Sheets API\n"
    "   - Habilita Google Drive API\n"
    "4) APIs & Services -> OAuth consent screen:\n"
    "   - Tipus: External (normalment)\n"
    "   - Omple dades b\u00e0siques\n"
    "   - Afegeix el teu usuari com a Test user (si est\u00e0 en mode Testing)\n"
    "5) APIs & Services -> Credentials -> Create credentials -> OAuth client ID:\n"
    "   - Application type: Desktop app\n"
    "6) Descarrega el JSON i guarda'l com: oauth_client.json\n"
    "   - Si uses l'EXE, deixa'l a la mateixa carpeta que UPC_FAQ_Scraper.exe\n\n"
    "Notes:\n"
    "- La primera vegada que executis, s'obrir\u00e0 el navegador per autoritzar.\n"
    "- El token es guardar\u00e0 a %APPDATA%\\UPCFAQScraper\\token.json."
)

FAQ_FORMAT_HELP_TEXT = (
    "Quines p\u00e0gines puc extreure?\n\n"
    "Aquest programa detecta autom\u00e0ticament aquests formats de FAQs:\n"
    "- UPC antic: #collapse-base (enlla\u00e7os que obren respostes)\n"
    "- Bootstrap 5: .accordion-item / .accordion-body\n"
    "- UPC/Plone nou: #faqAccordion (botons amb data-bs-target=\"#cX\")\n"
    "- Genweb GW4: .accordion.accordion-gw4 (links open-accordionX + .accordion-content)\n\n"
    "Si una p\u00e0gina t\u00e9 un format diferent, pot donar 0 resultats.\n"
    "En aquest cas cal afegir un selector nou al scraper."
)

UPC_BLUE = "#0F766E"
UPC_BLUE_TAB = "#115E59"
BG = "#F7F2E8"
LIGHT_PANEL = "#FFF9F0"
TEXT_MUTED = "#5F6F69"

TEXT_PRIMARY = "#21363A"
SURFACE = "#FFFDF8"
SURFACE_SUBTLE = "#E1EEE8"
BORDER = "#A5C0B7"
INPUT_BG = "#F8FCFA"
PLACEHOLDER = "#6D8780"
SCROLLBAR = "#8AA79E"
SCROLLBAR_HOVER = "#45675F"
LINK = "#0F766E"
DANGER = "#A4493D"
SUCCESS = "#216E62"
STATUS_NEUTRAL = "#5F6F69"
INFO_PANEL = "#E6F1EC"
SUCCESS_BG = "#DDF1EA"
SUCCESS_HOVER = "#C8E7DE"
SUCCESS_BORDER = "#7EA79B"
SUCCESS_TEXT = "#214B43"
DANGER_BG = "#F7E3DB"
DANGER_HOVER = "#F0D1C6"
DANGER_BORDER = "#C98A79"
DANGER_TEXT = "#7F3028"
